### ISSUE TITLE
关于查询tc的问题

### ISSUE THREAD

**Issue by alexanderhucheerful** [miniufo/besttracks#1]
您好，像这个语句tc = TCs_CMA.select(lambda tc:tc.name=='Rammasun' and tc.year==2014)[0]
如何查询nameless没有ID的热带气旋内，我print这个TCs_CMA对象只有id，name和year这几个属性，是否在在加载的时候把nameless的热带气旋剔除了呢，我要想修改的话应该在TCs_CMA的那个部分修改呢

**Comment by miniufo** [comment]
确实有你说的这个情况，如果没有命名，没有ID，本身就不方便查询，即使没有剔除也不知道用什么来索引它。你有什么好的建议吗？

**Comment by alexanderhucheerful** [comment]
好像每一个气旋都有独立编号，我觉得可以在给TCs_CMA这个类在加个属性通过气旋独立编号来查询

**Comment by miniufo** [comment]
这里有个1949年的例子：
```
66666 0000   10 0003 0000 0 6 (nameless)                         20110729
1949062006 1 213 1218 1000      12
1949062012 1 215 1235 1000      12
1949062018 1 218 1248 1000      12
1949062100 1 220 1260 1000      12
1949062106 1 225 1272 1002      12
1949062112 1 232 1286 1002      12
1949062118 1 235 1302 1004      12
1949062200 1 240 1320 1004      12
1949062206 1 260 1330 1004      12
1949062212 1 274 1332 1004      12
```
你说的独立编号是哪个？实际上这个库不仅仅需要考虑CMA，还需要考虑其他机构的编号和定义。有些低压没有出现在其他数据库中，所以只能是根据ID来唯一确定一个TC并用于查询和索引的。

**Comment by alexanderhucheerful** [comment]
0003，这个好像每个低压都有的编号，但如果是nameless它的id就是0000

**Comment by miniufo** [comment]
0003这个只是当年的第三个记录，如果换个数据库，比如日本的JMA，可能就不对应是第三个了。所以我当时应该是直接去掉了，没有编号也说明很弱，实际上弱低压每年都是上百个的，没有必要记录那么多

如果要把这样的TC解析返回，需要明确定义ID，这样不会与ID为0003的TC重名。我暂时没想到好的命名方式，既不重叠，又能保持0003这个信息。

**Comment by alexanderhucheerful** [comment]
您好，还想请教您一个问题，就是我用一个云模式cm1模拟了几个台风，但模式关于风速的输出变量有两个
一个是wspmax，它的描述是max grid-rel horiz wind speed 另一个是wsp10max 描述是max  horiz wind speed in 10m AGL，更多的信息就没有了文档里也找不到，因为我不太熟悉台风和模式，我查了下台风风速的定义是底层风速，并且这两个变量的值相差挺大的但趋势差不多，想请教一下您这两个变量用哪个能指代台风风速呢

**Comment by miniufo** [comment]
10米高的风是气象标准定义的海表风，台风强度也是用这层的风的最大值。不过台风风速最大值一般在边界层顶，大约900-850hPa附近，所以可能模式有两个变量，一般用10max来定义强度，就是海表风最大值

**Comment by alexanderhucheerful** [comment]
好的，太感谢了
