### ISSUE TITLE
Unable to install required packages

### ISSUE THREAD

**Issue by mockingcode** [miniufo/besttracks#4]
Pip cries a lot of error when installing required packages using this command:

 `pip install numpy==1.15.4 pandas==1.0.3 xarray==0.15.1 matplotlib==3.3.1 cartopy==0.18.0`

or with this one:

`pip install .`

Python version is at 3.9.12.
Pip version is at 20.0.2.

**Comment by miniufo** [comment]
Hi, you can try not specifying the version (or installing anaconda and use conda to install these packages).

**Comment by mockingcode** [comment]
I got the same errors when I removed the specific versions to install. Using `conda` did the job for me. 

Thanks!
